# Generated by Django 3.2.7 on 2022-09-02 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruiter',
            name='image',
        ),
        migrations.RemoveField(
            model_name='studentuser',
            name='image',
        ),
    ]
